// Auth-App-React/src/pages/Login.tsx
import "./Login.css";
import axios from "axios";
import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";

const Login = () => {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [formData, setFormData] = useState({ username: "", password: "" });
  const [message, setMessage] = useState("");

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({ ...formData, [e.target.id]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const response = await axios.get("http://localhost:5000/users", {
        params: { username: formData.username, password: formData.password },
      });
      if (response.data.length > 0) {
        setMessage("Login successful!");

        login({
          username: formData.username,
        });
        navigate("/home");
      } else {
        setMessage("Invalid credentials.");
      }
    } catch (error) {
      setMessage("Login failed. Try again.");
    }
  };

  return (
    <div className="principal">
      <div className="LoginDiv">
        <h1>Welcome</h1>
        <h3>Login to Your Account</h3>
        <form className="LoginCredentials" onSubmit={handleSubmit}>
          <label htmlFor="username">Username</label>
          <input
            className="LoginInput"
            type="text"
            id="username"
            placeholder="Enter your username"
            value={formData.username}
            onChange={handleChange}
          />
          <label htmlFor="password">Password</label>
          <input
            className="LoginInput"
            type="password"
            id="password"
            placeholder="Enter your password"
            value={formData.password}
            onChange={handleChange}
          />
          <input type="submit" value="Login" className="LoginSubmit" />
        </form>
        Don't have an account? <a href="/signup">Signup</a>
        {message && <p>{message}</p>}
      </div>
    </div>
  );
};

export default Login;

// Authentication-Angular/src/app/components/login/login.component.ts
// src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  formData = {
    username: '',
    password: '',
  };
  message: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  handleSubmit(): void {
    this.authService
      .login(this.formData.username, this.formData.password)
      .subscribe({
        next: (response) => {
          if (response.length > 0) {
            this.message = 'Login successful!';
            this.router.navigate(['/home']);
          } else {
            this.message = 'Invalid credentials.';
          }
        },
        error: (error) => {
          this.message = 'Login failed. Try again.';
          console.error(error);
        },
      });
  }
}

<div class="principal">
  <div class="LoginDiv">
    <h1>Welcome</h1>
    <h3>Login to Your Account</h3>
    <form
      class="LoginCredentials"
      (ngSubmit)="handleSubmit()"
      #loginForm="ngForm"
    >
      <label for="username">Username</label>
      <input
        class="LoginInput"
        type="text"
        id="username"
        name="username"
        placeholder="Enter your username"
        [(ngModel)]="formData.username"
        required
      />
      <label for="password">Password</label>
      <input
        class="LoginInput"
        type="password"
        id="password"
        name="password"
        placeholder="Enter your password"
        [(ngModel)]="formData.password"
        required
      />
      <button type="submit" class="LoginSubmit" [disabled]="!loginForm.valid">
        Login
      </button>
    </form>
    <p>Don't have an account? <a routerLink="/signup">Signup</a></p>
    <p *ngIf="message">{{ message }}</p>
  </div>
</div>
