// Authentication-Angular/src/app/components/home/home.component.ts
// src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { User } from '../../models/user.model';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  user: User | null = null;

  constructor(private authService: AuthService, private router: Router) {}

  ngOnInit(): void {
    this.authService.currentUser.subscribe((user) => {
      this.user = user;
    });
  }

  handleLogout(): void {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}

<div class="home-container">
  <nav class="navbar">
    <div class="HomeTitle">
      <h1>Authentication Application</h1>
    </div>
    <div class="HomeUser">
      <h3 *ngIf="user">{{ user.username }}</h3>
      <button class="Logoutbtn" (click)="handleLogout()">Logout</button>
    </div>
  </nav>
  <div class="content">
    <aside class="sidebar">
      <ul>
        <li>Dashboard</li>
        <li>Profile</li>
        <li>Settings</li>
        <li (click)="handleLogout()">Logout</li>
      </ul>
    </aside>
    <main class="main-content">
      <h2>Home Page</h2>
      <p>Welcome to your dashboard! You are now logged in.</p>
    </main>
  </div>
</div>

// Auth-App-React/src/pages/Home.tsx
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import "./Home.css";

const Home = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate("/login");
  };

  return (
    <div className="home-container">
      <nav className="navbar">
        <div className="HomeTitle">
          <h1>Authentication Application</h1>
        </div>
        <div className="HomeUser">
          <h3>{user?.username} </h3>
          <button className="Logoutbtn" onClick={handleLogout}>
            Logout
          </button>
        </div>
      </nav>
      <div className="content">
        <aside className="sidebar">
          <ul>
            <li>Dashboard</li>
            <li>Profile</li>
            <li>Settings</li>
            <li>Logout</li>
          </ul>
        </aside>
        <main className="main-content">
          <h2>Home Page</h2>
          <p>Home page content</p>
        </main>
      </div>
    </div>
  );
};

export default Home;
