// Authentication-Angular/src/app/components/signup/signup.component.ts
// src/app/components/signup/signup.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
})
export class SignupComponent {
  formData = {
    username: '',
    email: '',
    password: '',
  };
  message: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  handleSubmit(): void {
    this.authService
      .signup(
        this.formData.username,
        this.formData.email,
        this.formData.password
      )
      .subscribe({
        next: (response) => {
          this.message = 'Signup successful!';
          setTimeout(() => {
            this.router.navigate(['/login']);
          }, 1500);
        },
        error: (error) => {
          this.message = 'Signup failed. Try again.';
          console.error(error);
        },
      });
  }
}

<div class="principal">
  <div class="SignupDiv">
    <h1>Create an Account</h1>
    <h3>Sign up to get started</h3>
    <form class="Credentials" (ngSubmit)="handleSubmit()" #signupForm="ngForm">
      <label for="username">Username</label>
      <input
        class="SignupInput"
        type="text"
        id="username"
        name="username"
        placeholder="Enter your username"
        [(ngModel)]="formData.username"
        required
      />
      <label for="email">Email</label>
      <input
        class="SignupInput"
        type="email"
        id="email"
        name="email"
        placeholder="Enter your email"
        [(ngModel)]="formData.email"
        required
        email
      />
      <label for="password">Password</label>
      <input
        class="SignupInput"
        type="password"
        id="password"
        name="password"
        placeholder="Enter your password"
        [(ngModel)]="formData.password"
        required
        minlength="6"
      />
      <button type="submit" class="SignupSubmit" [disabled]="!signupForm.valid">
        Sign Up
      </button>
    </form>
    <p>Already have an account? <a routerLink="/login">Login</a></p>
    <p *ngIf="message">{{ message }}</p>
  </div>
</div>

// Auth-App-React/src/pages/Signup.tsx
import "./Signup.css";
import axios from "axios";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

const Signup = () => {
  const [formData, setFormData] = useState({
    username: "",
    email: "",
    password: "",
  });
  const [message, setMessage] = useState("");
  const navigate = useNavigate();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({ ...formData, [e.target.id]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const response = await axios.post(
        "http://localhost:5000/users",
        formData
      );
      if (response.status === 201) {
        setMessage("Signup successful!");
        navigate("/login");
      }
    } catch (error) {
      setMessage("Signup failed. Try again.");
    }
  };

  return (
    <div className="principal">
      <div className="SignupDiv">
        <h1>Create an Account</h1>
        <h3>Sign up to get started</h3>
        <form className="Credentials" onSubmit={handleSubmit}>
          <label htmlFor="username">Username</label>
          <input
            className="SignupInput"
            type="text"
            id="username"
            placeholder="Enter your username"
            value={formData.username}
            onChange={handleChange}
          />
          <label htmlFor="email">Email</label>
          <input
            className="SignupInput"
            type="email"
            id="email"
            placeholder="Enter your email"
            value={formData.email}
            onChange={handleChange}
          />
          <label htmlFor="password">Password</label>
          <input
            className="SignupInput"
            type="password"
            id="password"
            placeholder="Enter your password"
            value={formData.password}
            onChange={handleChange}
          />
          <input type="submit" value="Sign Up" className="SignupSubmit" />
        </form>
        {message && <p>{message}</p>}
      </div>
    </div>
  );
};

export default Signup;
